### ISSUE TITLE
Errors after installing package in vscode - Cannot activate extension

### ISSUE THREAD

**Issue by guntherwullaert** [IWANABETHATGUY/tower-lsp-boilerplate#5]
When installing the package with pnpm i; cargo build; pnpm build and pnpm package, I obtain a .vsix which is installable but throws an error upon activating on a .nrs file
```
2023-01-09 15:28:33.675 [error] Activating extension undefined_publisher.nrs-language-server failed due to an error:
2023-01-09 15:28:33.675 [error] TypeError: e.addEventListener is not a function
	at new s (.vscode\extensions\undefined.nrs-language-server-1.5.0\dist\extension.js:1:11278)
	at a.createMessageTransports (.vscode\extensions\undefined.nrs-language-server-1.5.0\dist\extension.js:1:59507)
	at a.createConnection (.vscode\extensions\undefined.nrs-language-server-1.5.0\dist\extension.js:1:117849)
	at a.resolveConnection (.vscode\extensions\undefined.nrs-language-server-1.5.0\dist\extension.js:1:112466)
	at a.start (.vscode\extensions\undefined.nrs-language-server-1.5.0\dist\extension.js:1:110616)
	at e.activate (.vscode\extensions\undefined.nrs-language-server-1.5.0\dist\extension.js:1:277601)
	at Ln.db (AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:15127)
	at Ln.cb (AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:14825)
	at AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:12823
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async v.n (AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:7006)
	at async v.m (AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:6969)
	at async v.l (AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:6426)
```
The same thing happens on my own fork. The question now is am I missing a step for compiling before I package ?
I also wanted to ask which webpack version you use, as this is not included in the devDependencies and maybe causes the issue ? 

For my own project I also obtain the error before the addEventListener error:
`[Error - 15:38:23] language server client: couldn't create connection to server.`

Maybe this is the cause ?

**Comment by PedroWitzel** [comment]
You probably forgot the `build` web-pack task (I did also 😄)
